# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Restic Backup
version: "0.0.1"
slug: restic-backup
description: Backup your HomeAssistant instance using Restic
url: "https://github.com/jannickfahlbusch/ha-restic-backup"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - config:ro
  - ssl:ro
  - addons:ro
  - media:ro
  - share:ro
  - backup:ro
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
